add capability for docker-compose run

diff --git a/funcs b/funcs
--- a/funcs
+++ b/funcs
@@ -83,3 +83,41 @@ ps() {
   cd $BASE_PATH/$comp
   docker-compose ps $@
 }
+
+
+# run command in a subsystem component
+run() {
+  comp=$1
+  shift
+
+  # parse options
+  compose_opts=""
+  while (( "$#" )); do
+    case "$1" in
+      -v)
+        compose_opts="$compose_opts -v $2"
+        shift 2
+        ;;
+      -w)
+        compose_opts="$compose_opts -w $2"
+        shift 2
+        ;;
+      --) # end argument parsing
+        shift
+        break
+        ;;
+      -*|--*=) # unsupported flags
+        echo "Error: Unsupported flag $1" >&2
+        exit 1
+        ;;
+      *) # preserve positional arguments
+        break
+        ;;
+    esac
+  done
+
+  cd $BASE_PATH/$comp
+  docker-compose run --no-deps \
+    -v "$BASE_PATH/config/docker-entrypoint.sh:/docker-entrypoint.sh:ro" \
+    $compose_opts $comp $@
+}
